#!/bin/bash

read -p "Enter the first number: " num1
read -p "Enter the second number: " num2

temp=$num1
num1=$num2
num2=$temp

echo "The first number is now: $num1"
echo "The second number is now: $num2"
